### PR TITLE
fix: Attempted to access a server-side environment

### LINKED ISSUE #308: Error: ❌ Attempted to access a server-side environment variable on the client
Sentry Issue: [SALEOR-APP-PAYMENT-ADYEN-1D](https://saleor.sentry.io/issues/4218870879/?referrer=github_integration)

```
Error: ❌ Attempted to access a server-side environment variable on the client
  at trpcClient.config (./src/modules/trpc/trpc-client.ts:33:13)
...
(11 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by mmiszy**
Fixes #308

### CODE REVIEW

File: src/lib/logger.ts [hunk 1]
```diff
@@ -1,19 +1,22 @@
...
-      : undefined,
+  // transport:
+  //   process.env.CI || nodeEnv === "development" || nodeEnv === "test"
+  //     ? {
+  //         target: "pino-pretty",
+  //         options: {
+  //           colorize: true,
+  //         },
+  //       }
+  //     : undefined,
```
Comment (mmiszy) [inline src/lib/logger.ts:19]: All of a sudden this started throwing:
```
unable to determine transport target for "pino-pretty"
```

**Review by witoszekdev — APPROVED** [review]
