### PR TITLE
Fix dark mode

### LINKED ISSUE #48: Support dark mode
Update app styles when dark mode is used in Saleor Dashboard

Image

### PR DESCRIPTION
**Pull request by witoszekdev**
Fixed #48

### CODE REVIEW

File: src/modules/ui/Input/Input.tsx [hunk 1]
```diff
@@ -11,13 +11,22 @@ interface InputProps {
...
           <span className={classNames(labelStyles, hideLabel && visuallyHiddenLabel)}>
             {labelText}
           </span>
-          <input {...props} className={input} ref={ref} />
+          <input
+            {...props}
+            className={input({
+              disabled,
+              error: !!error,
+            })}
```
Comment (mmiszy) [inline src/modules/ui/Input/Input.tsx:27]: Is there a reason we're not using `Input` from the macaw-ui and instead replicating the design here on our own?

**Review by mmiszy — CHANGES_REQUESTED** [review]

File: src/modules/ui/Input/Input.tsx (hunk 1 above)
Comment (witoszekdev) [reply src/modules/ui/Input/Input.tsx:27]: Replacing existing input would completely break our layout right now (e.g. Select) so until we replace everything to use macaw I would leave it

**Review by mmiszy — APPROVED** [review]
